apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/aws/s3.png
  alias: AWS S3 Bucket Health For Region {{match_resource.resource.region}}
  asMeasuredBy: The number of AWS S3 Buckets in region {{match_resource.resource.region}}
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: The total count of unhealthy or insecure S3 buckets should be 0.   
  additionalContext:
    region: "{{match_resource.resource.region}}"