apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://logowik.com/content/uploads/images/aws-ec24128.jpg
  alias: AWS EC2 Health For Region {{match_resource.resource.region}}
  asMeasuredBy: The number of old EC2 instances in region {{match_resource.resource.region}}
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: Helps identify aged EC2 instances in the region for proactive resource cleanup and cost optimization.
  additionalContext:
    region: "{{match_resource.resource.region}}"
    account_id: "{{match_resource.resource.account_id}}"