apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/aws/Resource-Icons_06072024/Res_Management-Governance/Res_Amazon-CloudWatch_48.svg
  alias: AWS Monitoring Logs Health For Region {{match_resource.resource.region}} in Account {{match_resource.resource.account_id}}
  asMeasuredBy: CloudWatch Log Groups without retention period, Cloudtrail that is not multi-region and CloudTrail Trails without CloudWatch Logs in AWS region {{match_resource.resource.region}} and account {{match_resource.resource.account_id}}
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: Identify CloudWatch and CloudTrail configuration or health issues in AWS region {{match_resource.resource.region}} and account {{match_resource.resource.account_id}}
  additionalContext:
    region: "{{match_resource.resource.region}}"
    account_id: "{{match_resource.resource.account_id}}" 