apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://www.shareicon.net/data/128x128/2015/08/28/92177_content_512x512.png
  alias: AWS EBS Health For Region {{match_resource.resource.region}}
  asMeasuredBy: The number of AWS EBS volumes and snapshots in region {{match_resource.resource.region}}
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: The total count of unattached, unencrypted volumes and unused snapshots should be 0. 
  additionalContext:
    region: "{{match_resource.resource.region}}"
    account_id: "{{match_resource.resource.account_id}}"