apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://PLACEHOLDER.png
  alias: AWS Network Health For AWS Account {{match_resource.resource.account_id}}
  asMeasuredBy: The number of publicly accessible security groups, unused EIPs, and ELBs in AWS account {{match_resource.resource.account_id}}
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: Identify publicly accessible security groups, unused EIPs, and ELBs in the AWS account {{match_resource.resource.account_id}}
  additionalContext:
    region: "{{match_resource.resource.region}}"
    account_id: "{{match_resource.resource.account_id}}"