apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://PLACEHOLDER.png
  alias: AWS Network Health For Region {{match_resource.resource.region}} in Account {{match_resource.resource.account_id}}
  asMeasuredBy: The number of security groups allowing public IP access and unused Elastic IPs in region {{match_resource.resource.region}} and account {{match_resource.resource.account_id}}
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: The total count of unhealthy AWS network resources. 
  additionalContext:
    region: "{{match_resource.resource.region}}"
    account_id: "{{match_resource.resource.account_id}}"